INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1000,"tellus,","scelerisque sed, sapien. Nunc pulvinar arcu et pede.","721.09","185.70",515);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1003,"at","Integer tincidunt","374.85","827.57",953);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1006,"augue","commodo hendrerit. Donec porttitor tellus non magna. Nam ligula","174.17","555.95",311);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1009,"pretium","Duis cursus, diam at pretium aliquet, metus urna","344.06","522.14",10);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1012,"vulputate","Vestibulum ut eros non enim commodo hendrerit. Donec","261.00","927.63",367);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1015,"at","diam dictum sapien. Aenean massa. Integer vitae","742.41","765.00",325);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1018,"scelerisque","nulla at sem molestie","553.05","201.95",358);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1021,"Morbi","montes, nascetur ridiculus mus. Proin vel","355.66","27.80",316);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1024,"ornare","magna tellus faucibus leo,","689.13","352.04",143);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1027,"turpis.","pede. Praesent eu dui. Cum sociis","840.38","342.54",354);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1030,"Donec","Fusce feugiat.","809.79","792.33",363);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1033,"feugiat","nec tempus","887.79","216.96",410);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1036,"non,","erat, eget tincidunt dui augue eu tellus. Phasellus elit pede,","478.92","724.38",201);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1039,"enim","amet, consectetuer adipiscing elit.","591.21","762.50",90);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1042,"Duis","sodales elit erat vitae risus. Duis a","861.78","376.05",385);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1045,"Ut","Curabitur ut odio vel est tempor bibendum.","770.97","741.51",527);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1048,"Vestibulum","orci","170.41","292.96",997);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1051,"sed","Curabitur egestas nunc sed libero. Proin sed turpis nec","451.03","276.29",951);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1054,"non","pretium neque. Morbi quis urna. Nunc","537.04","529.40",916);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1057,"vitae","arcu iaculis enim, sit","492.16","125.76",447);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1060,"Sed","dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus","632.38","997.84",935);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1063,"Suspendisse","Nulla facilisi. Sed neque. Sed","165.10","973.77",282);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1066,"sagittis","quis lectus. Nullam suscipit, est ac facilisis facilisis,","354.45","591.63",379);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1069,"turpis","vel nisl. Quisque fringilla euismod enim.","479.65","413.82",561);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1072,"ipsum.","aliquam, enim nec tempus scelerisque,","42.94","867.04",760);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1075,"velit","felis eget","242.77","657.59",794);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1078,"lorem,","Cras dolor dolor, tempus non, lacinia at,","469.63","861.91",44);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1081,"Aliquam","mauris id sapien. Cras dolor dolor, tempus non, lacinia","809.49","461.19",709);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1084,"in","sagittis placerat. Cras dictum ultricies","667.14","531.55",963);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1087,"mattis","magna sed dui. Fusce aliquam,","205.41","17.83",24);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1090,"arcu.","ipsum ac mi eleifend egestas. Sed","737.94","982.82",644);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1093,"amet,","pede, nonummy","39.33","655.36",500);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1096,"vulputate","lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate","880.19","770.86",764);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1099,"ornare,","auctor, nunc nulla vulputate","534.41","107.70",789);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1102,"aliquam","egestas. Aliquam nec enim. Nunc","525.69","373.10",476);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1105,"dapibus","cursus purus. Nullam scelerisque neque sed sem","26.39","881.84",787);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1108,"pulvinar","habitant","864.28","811.27",657);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1111,"vulputate,","ipsum cursus vestibulum.","225.05","899.65",879);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1114,"eget","sit","807.41","141.49",299);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1117,"consectetuer","dolor elit, pellentesque a, facilisis","133.84","348.75",255);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1120,"at","sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum","584.73","119.55",22);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1123,"feugiat","tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris.","214.65","406.35",384);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1126,"ornare","Nulla facilisi.","686.71","462.07",22);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1129,"mollis","sagittis augue, eu tempor erat","626.89","582.36",202);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1132,"est,","Sed id risus quis diam luctus lobortis. Class aptent taciti","729.01","760.94",313);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1135,"sit","nec","4.28","781.41",437);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1138,"sit","lacinia mattis. Integer eu lacus. Quisque imperdiet,","346.56","584.36",168);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1141,"sapien","id magna et ipsum cursus vestibulum.","221.13","511.27",934);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1144,"pede.","eros turpis non","581.84","696.17",412);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1147,"arcu.","amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat.","132.76","779.48",778);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1150,"magna","at fringilla purus mauris a nunc. In at","897.75","809.11",852);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1153,"quis","Mauris non dui nec","176.11","431.98",908);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1156,"felis,","sollicitudin adipiscing","540.66","955.55",982);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1159,"orci,","dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque","113.13","484.37",902);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1162,"magna","non enim. Mauris quis turpis vitae","636.38","222.48",231);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1165,"blandit","lectus ante dictum mi, ac mattis velit","83.16","97.58",505);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1168,"facilisis,","Morbi accumsan","738.70","287.38",760);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1171,"Nunc","interdum. Curabitur dictum. Phasellus","752.70","948.91",486);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1174,"tempor","porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est.","327.12","984.72",274);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1177,"nec,","sit amet, consectetuer","989.57","451.10",456);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1180,"tristique","Mauris eu turpis. Nulla","476.97","404.03",674);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1183,"Quisque","aliquet magna a neque. Nullam ut nisi a","331.88","719.20",273);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1186,"orci.","est, congue a, aliquet","280.81","637.60",561);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1189,"risus.","felis purus ac tellus. Suspendisse sed","437.57","79.15",651);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1192,"gravida","nisl. Maecenas malesuada fringilla est. Mauris","886.89","160.72",293);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1195,"auctor","Vestibulum ante ipsum primis in faucibus orci luctus et ultrices","294.31","432.02",789);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1198,"egestas.","magna. Duis dignissim tempor arcu. Vestibulum ut eros non","711.87","59.42",359);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1201,"Vivamus","viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor","728.55","504.40",612);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1204,"at,","quis lectus. Nullam suscipit,","501.90","250.79",455);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1207,"ligula","Sed eu eros. Nam consequat dolor","107.11","748.21",956);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1210,"fringilla","eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean","682.42","981.39",1);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1213,"Donec","ut dolor dapibus gravida. Aliquam","225.17","361.39",820);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1216,"est","ridiculus mus. Donec dignissim magna","542.46","16.73",779);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1219,"luctus","tincidunt, neque vitae semper egestas,","931.19","973.29",288);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1222,"lorem,","at pede. Cras vulputate velit eu sem. Pellentesque ut","637.39","591.71",757);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1225,"sollicitudin","arcu eu odio tristique pharetra. Quisque ac libero","693.20","464.37",436);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1228,"lectus","Quisque ac libero nec ligula consectetuer","407.55","781.82",611);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1231,"volutpat.","quis, pede. Suspendisse dui. Fusce diam","90.18","198.67",989);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1234,"lectus","fames ac turpis egestas. Aliquam fringilla","769.62","273.80",162);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1237,"Duis","quam a felis ullamcorper viverra. Maecenas iaculis aliquet","498.20","82.48",746);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1240,"Cum","Vivamus euismod urna. Nullam lobortis quam a","329.77","165.04",641);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1243,"nisi.","consectetuer, cursus et, magna.","541.83","849.88",409);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1246,"mauris.","Sed nunc est, mollis non, cursus non, egestas a, dui.","915.09","605.82",780);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1249,"tristique","Suspendisse","92.22","96.55",570);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1252,"vitae","parturient montes, nascetur ridiculus mus. Proin vel arcu","803.02","795.47",303);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1255,"tempor","sagittis lobortis mauris. Suspendisse","724.78","959.04",379);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1258,"Integer","fringilla est. Mauris eu","926.54","517.94",934);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1261,"Ut","malesuada vel, convallis in, cursus et, eros. Proin","124.68","672.88",233);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1264,"Nullam","Donec est. Nunc ullamcorper, velit in","875.35","780.00",521);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1267,"cursus","risus. Nulla eget metus eu","625.88","484.01",334);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1270,"lobortis","quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu,","883.77","123.40",148);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1273,"vitae,","lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit","744.05","812.54",324);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1276,"ornare.","amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede,","547.11","60.49",622);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1279,"turpis","consectetuer adipiscing elit. Etiam","353.00","937.41",149);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1282,"dolor","Pellentesque habitant","671.25","193.67",85);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1285,"ultrices","nisi. Aenean eget metus. In nec orci. Donec nibh.","119.50","957.65",437);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1288,"at","nec enim. Nunc ut erat. Sed nunc est, mollis non,","909.20","935.18",56);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1291,"nec,","malesuada fames ac turpis egestas. Aliquam fringilla cursus","646.51","72.13",121);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1294,"interdum.","vitae risus. Duis a mi","984.41","112.02",236);
INSERT INTO Products (ProductCode,Name,Description,SuggestedUnitPrice,BuyUnitPrice,UnitsInStock) VALUES (1297,"magna","varius","933.89","780.09",597);