INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1000,1000,"nibh sit amet orci. Ut sagittis lobortis mauris.");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1005,1003,"eu elit. Nulla facilisi.");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1010,1006,"orci.");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1015,1009,"magna sed dui. Fusce aliquam, enim nec tempus scelerisque,");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1020,1012,"semper tellus id nunc interdum feugiat.");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1025,1015,"imperdiet ornare.");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1030,1018,"dignissim pharetra.");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1035,1021,"elit. Etiam");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1040,1024,"adipiscing ligula. Aenean gravida");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1045,1027,"ultrices sit amet,");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1050,1030,"Aliquam auctor,");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1055,1033,"Quisque fringilla euismod enim. Etiam gravida");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1060,1036,"ligula. Nullam feugiat placerat velit. Quisque");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1065,1039,"turpis. In condimentum. Donec at arcu. Vestibulum ante");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1070,1042,"ornare. Fusce mollis. Duis sit amet diam eu dolor");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1075,1045,"orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare,");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1080,1048,"malesuada fames");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1085,1051,"consequat enim diam vel arcu. Curabitur ut");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1090,1054,"lectus. Cum sociis natoque");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1095,1057,"mollis. Duis sit amet diam eu dolor egestas");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1100,1060,"aliquet molestie tellus. Aenean egestas");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1105,1063,"aliquet odio. Etiam");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1110,1066,"eu,");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1115,1069,"Donec nibh enim,");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1120,1072,"tincidunt");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1125,1075,"facilisis eget, ipsum. Donec sollicitudin adipiscing");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1130,1078,"feugiat. Sed nec metus facilisis");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1135,1081,"erat vel");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1140,1084,"arcu. Vestibulum ante ipsum primis in faucibus");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1145,1087,"id, ante. Nunc");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1150,1090,"fermentum arcu. Vestibulum ante");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1155,1093,"velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas.");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1160,1096,"Nam ligula elit, pretium et, rutrum");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1165,1099,"nunc sit amet");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1170,1102,"Donec porttitor tellus non magna. Nam ligula");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1175,1105,"eget massa. Suspendisse");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1180,1108,"in molestie tortor");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1185,1111,"Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed,");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1190,1114,"Mauris magna. Duis dignissim tempor arcu.");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1195,1117,"non dui nec urna suscipit");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1200,1120,"Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1205,1123,"fringilla purus mauris");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1210,1126,"non magna. Nam ligula elit, pretium");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1215,1129,"faucibus orci luctus et");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1220,1132,"arcu ac orci. Ut");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1225,1135,"magnis dis parturient montes,");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1230,1138,"amet risus. Donec egestas. Aliquam");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1235,1141,"neque venenatis");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1240,1144,"tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1245,1147,"in faucibus orci");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1250,1150,"lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1255,1153,"turpis. Nulla aliquet. Proin velit. Sed");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1260,1156,"erat nonummy ultricies ornare, elit elit fermentum risus, at");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1265,1159,"tortor");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1270,1162,"vitae sodales nisi magna sed dui.");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1275,1165,"odio. Phasellus at augue id ante dictum cursus.");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1280,1168,"sagittis. Nullam vitae diam. Proin dolor. Nulla");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1285,1171,"nec mauris blandit");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1290,1174,"vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1295,1177,"elementum, dui quis accumsan convallis, ante lectus convallis est,");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1300,1180,"Donec consectetuer mauris id sapien. Cras");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1305,1183,"nec tellus. Nunc lectus pede,");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1310,1186,"In scelerisque scelerisque dui. Suspendisse ac");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1315,1189,"Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1320,1192,"Sed eu eros. Nam consequat dolor");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1325,1195,"nec, mollis vitae, posuere at, velit. Cras lorem lorem,");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1330,1198,"lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1335,1201,"ultrices sit amet, risus. Donec nibh enim, gravida");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1340,1204,"mauris eu elit. Nulla facilisi. Sed neque. Sed");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1345,1207,"urna convallis erat, eget tincidunt dui");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1350,1210,"Morbi");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1355,1213,"imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1360,1216,"Sed eget lacus.");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1365,1219,"vel, vulputate eu,");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1370,1222,"mauris sit amet lorem semper auctor. Mauris");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1375,1225,"sollicitudin commodo ipsum.");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1380,1228,"ante. Vivamus non lorem vitae odio sagittis");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1385,1231,"laoreet lectus quis massa. Mauris vestibulum, neque sed dictum");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1390,1234,"Aliquam tincidunt, nunc ac mattis");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1395,1237,"sit amet, consectetuer adipiscing elit. Curabitur");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1400,1240,"purus. Duis");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1405,1243,"dui. Suspendisse ac metus vitae velit");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1410,1246,"mattis. Cras eget nisi dictum augue malesuada");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1415,1249,"neque.");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1420,1252,"ridiculus mus. Donec dignissim magna a tortor. Nunc");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1425,1255,"rutrum,");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1430,1258,"eu, ligula.");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1435,1261,"porttitor tellus non magna. Nam ligula elit, pretium et, rutrum");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1440,1264,"tincidunt. Donec vitae erat vel pede");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1445,1267,"sed,");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1450,1270,"venenatis vel, faucibus");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1455,1273,"ut aliquam iaculis, lacus pede sagittis augue, eu tempor");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1460,1276,"sed orci lobortis augue scelerisque mollis. Phasellus");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1465,1279,"velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus.");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1470,1282,"penatibus et magnis dis");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1475,1285,"bibendum. Donec felis orci, adipiscing non,");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1480,1288,"eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1485,1291,"adipiscing");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1490,1294,"Fusce aliquam, enim nec tempus scelerisque, lorem ipsum");
INSERT INTO ProductSupplier (SupplierId,ProductCode,Notes) VALUES (1495,1297,"lobortis");