INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1000,"Lorem ipsum dolor");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1003,"Lorem ipsum dolor sit amet,");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1006,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit.");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1009,"Lorem ipsum");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1012,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit.");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1015,"Lorem");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1018,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit.");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1021,"Lorem ipsum dolor sit");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1024,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit.");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1027,"Lorem ipsum dolor sit amet,");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1030,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1033,"Lorem ipsum dolor sit amet, consectetuer");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1036,"Lorem ipsum dolor sit");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1039,"Lorem ipsum dolor sit amet,");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1042,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1045,"Lorem ipsum dolor sit amet, consectetuer adipiscing");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1048,"Lorem ipsum");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1051,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1054,"Lorem ipsum dolor sit amet, consectetuer");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1057,"Lorem ipsum");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1060,"Lorem ipsum dolor sit amet, consectetuer adipiscing");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1063,"Lorem ipsum dolor sit amet, consectetuer adipiscing");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1066,"Lorem ipsum dolor sit amet,");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1069,"Lorem ipsum dolor sit amet,");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1072,"Lorem ipsum dolor sit amet, consectetuer");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1075,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1078,"Lorem ipsum dolor");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1081,"Lorem ipsum dolor sit amet,");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1084,"Lorem ipsum dolor sit amet, consectetuer");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1087,"Lorem ipsum");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1090,"Lorem ipsum dolor sit amet, consectetuer adipiscing");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1093,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1096,"Lorem ipsum");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1099,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1102,"Lorem ipsum dolor sit amet, consectetuer");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1105,"Lorem ipsum dolor sit amet,");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1108,"Lorem ipsum dolor sit amet,");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1111,"Lorem ipsum dolor sit amet, consectetuer adipiscing");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1114,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1117,"Lorem");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1120,"Lorem ipsum dolor sit amet, consectetuer adipiscing");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1123,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit.");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1126,"Lorem ipsum dolor sit amet, consectetuer adipiscing");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1129,"Lorem ipsum dolor sit");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1132,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit.");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1135,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1138,"Lorem ipsum");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1141,"Lorem ipsum");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1144,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit.");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1147,"Lorem ipsum");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1150,"Lorem ipsum");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1153,"Lorem ipsum dolor sit amet,");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1156,"Lorem ipsum dolor");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1159,"Lorem ipsum dolor sit amet, consectetuer");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1162,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1165,"Lorem ipsum dolor sit amet, consectetuer adipiscing");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1168,"Lorem ipsum");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1171,"Lorem");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1174,"Lorem ipsum dolor");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1177,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1180,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit.");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1183,"Lorem ipsum dolor sit");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1186,"Lorem ipsum dolor sit amet,");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1189,"Lorem ipsum dolor");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1192,"Lorem ipsum");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1195,"Lorem ipsum");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1198,"Lorem ipsum dolor sit amet, consectetuer");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1201,"Lorem ipsum dolor sit");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1204,"Lorem ipsum dolor");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1207,"Lorem ipsum dolor");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1210,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1213,"Lorem ipsum dolor");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1216,"Lorem ipsum dolor sit amet, consectetuer");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1219,"Lorem");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1222,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit.");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1225,"Lorem ipsum");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1228,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit.");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1231,"Lorem");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1234,"Lorem ipsum dolor");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1237,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1240,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1243,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1246,"Lorem ipsum dolor sit");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1249,"Lorem ipsum dolor sit amet, consectetuer adipiscing");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1252,"Lorem ipsum dolor sit");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1255,"Lorem ipsum dolor sit amet, consectetuer");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1258,"Lorem ipsum dolor sit amet,");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1261,"Lorem ipsum dolor sit amet,");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1264,"Lorem ipsum dolor sit");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1267,"Lorem ipsum dolor sit amet,");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1270,"Lorem ipsum");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1273,"Lorem ipsum");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1276,"Lorem ipsum dolor sit amet,");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1279,"Lorem ipsum dolor sit amet,");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1282,"Lorem ipsum");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1285,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit.");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1288,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1291,"Lorem ipsum dolor");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1294,"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed");
INSERT INTO ProductDetails (ProductCode,MoreDescription) VALUES (1297,"Lorem ipsum dolor sit amet,");